### ISSUE TITLE
No module named configparser

### ISSUE THREAD

**Issue by elpaul** [Saiyato/volumio-hd44780-plugin#8]
Hello.
After install (on volumio 2.565) in my LCD is only: Welcome to VOLUMIO2!

in command terminal I see:
volumio@volumio:~$ mpdlcd
Traceback (most recent call last):
  File "/usr/local/bin/mpdlcd", line 7, in <module>
    from mpdlcd import cli
  File "/usr/local/lib/python2.7/dist-packages/mpdlcd/cli.py", line 5, in <module>
    import configparser
ImportError: No module named configparser

Can someone help me?

**Comment by joirma** [comment]
I solve this dependency error installing python-configparser
apt-get install python-configparser
But i have other dependency error:
  File "/usr/local/bin/mpdlcd", line 7, in <module>
    from mpdlcd import cli
  File "/usr/local/lib/python2.7/dist-packages/mpdlcd/cli.py", line 6, in <module>
    import urllib.parse
ImportError: No module named parse
